packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@clerk/shared'
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
